In [3]:
import pandas as pd
import numpy as np
import pipes as pp

In [4]:
df = pd.read_csv('air_train.csv')
df.drop(['Unnamed: 0', 'id'], axis = 1, inplace = True)

In [5]:
df = pp.myPipe.transform(df)

In [6]:
df

,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,...,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,G,TT,Delay
0,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,5,...,4,4,5,5,25,18.0,neutral or dissatisfied,0,1,43.0
1,disloyal Customer,25,Business travel,Business,235,3,2,3,3,1,...,3,1,4,1,1,6.0,neutral or dissatisfied,0,0,7.0
2,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,5,...,4,4,4,5,0,0.0,satisfied,1,0,0.0
3,Loyal Customer,25,Business travel,Business,562,2,5,5,5,2,...,3,1,4,2,11,9.0,neutral or dissatisfied,1,0,20.0
4,Loyal Customer,61,Business travel,Business,214,3,3,3,3,4,...,4,3,3,3,0,0.0,satisfied,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,disloyal Customer,23,Business travel,Eco,192,2,1,2,3,2,...,4,2,3,2,3,0.0,neutral or dissatisfied,1,0,3.0
103900,Loyal Customer,49,Business travel,Business,2347,4,4,4,4,2,...,5,5,5,4,0,0.0,satisfied,0,0,0.0
103901,disloyal Customer,30,Business travel,Business,1995,1,1,1,3,4,...,4,5,5,4,7,14.0,neutral or dissatisfied,0,0,21.0
103902,disloyal Customer,22,Business travel,Eco,1000,1,1,1,5,1,...,1,5,4,1,0,0.0,neutral or dissatisfied,1,0,0.0
103903,Loyal Customer,27,Business travel,Business,1723,1,3,3,3,1,...,4,4,3,1,0,0.0,neutral or dissatisfied,0,0,0.0